### PR TITLE
Test with more than one app on Travis CI

### PR DESCRIPTION
**Pull request by probonopd**
Three out of four are currently failing, but I'd say it is good to test more than one (and maybe fix the other three)

### CODE REVIEW

**Comment by sudo-give-me-coffee** [comment]
> Three out of four are currently failing

I success fully bundled 80% of ElementaryOS apps available on Flathub, the success can be increased (i think) enabling internet under chroot

**Comment by sudo-give-me-coffee** [comment]
Some applications (like Natron) will never be included in my approach, they rely on a compatible gpu driver to run. I will merge, but in these cases it is not possible to fix without FUSE or any overlayer filesystem

**Comment by sudo-give-me-coffee** [comment]
How many jobs can be added?

**Comment by probonopd** [comment]
In respect to the free Travis CI service we should not over-use it nor come close to their limits. If we want to have significantly more applications, we should run them in sequence rather than in parallel (as I am currently doing) because running in parallel means that the runtime/SDK is downloaded each time.

Do you understand how Flatpak handles the GPU drivers?

**Pull request merged**
